In [1]:
import numpy as np

In [7]:
arr=np.array([7,8,9,6],dtype='int64')

In [3]:
print(arr)

[7 8 9 6]


In [4]:
arr

array([7, 8, 9, 6])

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr.shape

(4,)

In [26]:
#EMPTY ARRAY
zero=np.zeros((7,52))

In [29]:
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 

In [19]:
rng=np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
lp=np.linspace(0,5,6)
lp

array([0., 1., 2., 3., 4., 5.])

In [22]:
emp=np.empty_like(lp)
emp

array([0., 1., 2., 3., 4., 5.])

In [25]:
ep=np.empty((4,6))
ep

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33644129e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37960147e-306, 1.33511562e-306, 2.22518251e-306,
        1.33511969e-306, 1.78022342e-306, 1.05700345e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 2.22518251e-306, 1.33511969e-306],
       [1.60220393e-306, 1.33511562e-306, 7.56602523e-307,
        1.95820760e-306, 9.34601642e-307, 1.42410974e-306]])

In [32]:
id=np.identity(8,dtype='int32')
print(id)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [35]:
id.ravel()

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [37]:
arr1=np.array([[1,2,4],[4,2,1],[7,8,9]])
arr2=np.array([[15,64,7],[8,5,4],[9651,4,2]])

In [38]:
print(arr1*arr2)

[[   15   128    28]
 [   32    10     4]
 [67557    32    18]]


In [45]:
print(arr1.sum())
print(arr2.sum())
print(arr1.sum(axis=0))
print(arr2.sum(axis=0))
print(arr1.sum(axis=1))
print(arr2.sum(axis=1))

38
9760
[12 12 14]
[9674   73   13]
[ 7  7 24]
[  86   17 9657]


In [47]:
arr1.T
arr2.T

array([[  15,    8, 9651],
       [  64,    5,    4],
       [   7,    4,    2]])

In [49]:
np.where(arr1>4)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [50]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [51]:
arr1

array([[1, 2, 4],
       [4, 2, 1],
       [7, 8, 9]])

In [59]:
#argmax():return the the index of the maximum value of the array
#argsort():return the index of the sorted array
a=np.array([47,12,20,89,0])
a.argsort()
a.argmax()

3